name: Deploy Azure Resource Manager (ARM)

on:
  push:
    branches: [ dev, test, main ]
    paths:
      - ".github/workflows/deploy-azure-resource.yml"

permissions:
  contents: read
  id-token: write

jobs:
  Setup-Azure-resource:
    needs: setup-environment
    environment: <YourEnv>
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4.1.1

    - name: 'Azure Login'
      uses: Azure/login@v1.6.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: 'Deploy Azure Resource Manager (ARM)'
      uses: Azure/arm-deploy@v1.0.9
      with:
        scope: 'resourcegroup'
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: 'my-resource-group-${{ <YourEnv> }}'
        template: ./infra/main.bicep
        parameters: >
          environmentName=${{ <YourEnv> }}
        failOnStdErr: false
