name: Test - Run Azure Login with OpenID Connect and deploy bicep

on:
  workflow_dispatch:
  # push:
  #   branches: [ dev, test ]
  # pull_request:
  #   branches: [ main ]

permissions:
      id-token: write
      contents: read

jobs:
  get_branch_name:
    uses: ./.github/workflows/github-branch-check.yml
    
  Print_branch_name:
    runs-on: ubuntu-latest
    needs: get_branch_name
    steps:
    - run: |
        echo the 1st is ${{ needs.get_branch_name.outputs.firstword }} 
        echo the 2nd is ${{ needs.get_branch_name.outputs.secondword }}

  build_dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use secret from 'dev' environment
      run: |
        echo "Using secret from dev environment"
        # Use the secret here
        echo "Secret: ${{ secrets.MING_SECRET }}"
        echo "Variable: ${{ vars.MING_VAR }}"

  build_test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    environment: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use secret from 'test' environment
      run: |
        echo "Using secret from test environment"
        # Use the secret here
        echo "Secret: ${{ secrets.MING_SECRET }}"
        echo "Variable: ${{ vars.MING_VAR }}"
        
  demo_build:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY

    - name: Extract branch name
      run: echo "branch name ==> ${{ github.ref_name }}" 
    - name: Extract branch name
      run: echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed 's|refs/heads/||')" >> $GITHUB_ENV

    - name: Use environment-specific secret
      run: |
        echo "Using secret from the ${{ job.environment.name }} environment"
        # Use the secret here
        echo "Secret: ${{ secrets.MING_SECRET }}"
        echo "Secret: ${{ secrets.MING_SECRET }}"

    - name: Use secret from 'dev' environment
      if: github.ref == 'refs/heads/dev'
      run: |
        echo "Using secret from dev environment"
        # Use the secret here
        echo "Secret: ${{ secrets.MING_SECRET }}"
      env:
        MING_SECRET: ${{ secrets.MING_SECRET }}
      environment: 
        name: dev

    - name: Use secret from 'test' environment
      if: github.ref == 'refs/heads/test'
      run: |
        echo "Using secret from test environment"
        # Use the secret here
        echo "Secret: ${{ secrets.MING_SECRET }}"
      env:
        MING_SECRET: ${{ secrets.MING_SECRET }}
      environment: 
        name: test



        
      # - name: 'Step#2 - Login'
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     enable-AzPSSession: true

      # - name: Step#3 - deploy bicep
      #   uses: azure/arm-deploy@v1
      #   with:
      #     scope: 'resourcegroup'
      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     resourceGroupName: 'my-resource-group-test'
      #     template: ./infra/main.bicep
      #     parameters: ./infra/paramsTest.json
      #     failOnStdErr: false
